## Connect duckdb in python

In [20]:
import duckdb

with duckdb.connect("database/jokes.duckdb") as conn:
    conn.sql("DROP TABLE IF EXISTS jokes;")
    
    conn.sql("""--sql
        CREATE TABLE IF NOT EXISTS jokes (
             id INT,
             joke STRING
        );
    """)

    conn.sql("""--sql
        INSERT INTO jokes VALUES
             (1, 'Why do programmers hate sunlight, because they attract bugs'),
             (2, 'Why do java programmers need glasses, because they cannot C#'); 
    """)

    desc = conn.sql("DESC;").df()

In [3]:
desc

  database schema   name column_names        column_types  temporary
0    jokes   main  jokes   [id, joke]  [INTEGER, VARCHAR]      False

In [24]:
with duckdb.connect("database/jokes.duckdb") as conn: 
    jokes = conn.sql("FROM jokes;").df()

# outside -> db connection is closed
# but have saved dataframe to jokes variable
jokes

   id                                               joke
0   1  Why do programmers hate sunlight, because they...
1   2  Why do java programmers need glasses, because ...

In [9]:
jokes["joke"]

0    Why do programmers hate sunlight, because they...
1    Why do java programmers need glasses, because ...
Name: joke, dtype: object