# pandas + duckdb

## load sakila sqlite -> duckdb

In [ ]:
import duckdb

# "r" - read mode for the file we open
with open("sql/load_sakila.sql", "r") as sql_file:
    loading_script = sql_file.read()

print(loading_script)

INSTALL sqlite;

LOAD sqlite;

CALL sqlite_attach ('data/sqlite-sakila.db');

In [3]:
type(loading_script)

str

connect to duckdb

In [ ]:
from pathlib import Path

duckdb_path = "data/sakila.duckdb"

# throws away sakila.duckdb if it exists -> makes it idempotent
Path(duckdb_path).unlink(missing_ok=True)

with duckdb.connect(duckdb_path) as conn:
    conn.sql(loading_script)

    description = conn.sql("desc;").df()
    films = conn.sql("FROM film;").df()

description

,database,schema,name,column_names,column_types,temporary
0,sakila,main,actor,"[actor_id, first_name, last_name, last_update]","[DOUBLE, VARCHAR, VARCHAR, TIMESTAMP]",False
1,sakila,main,address,"[address_id, address, address2, district, city...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT, VA...",False
2,sakila,main,category,"[category_id, name, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",False
3,sakila,main,city,"[city_id, city, country_id, last_update]","[BIGINT, VARCHAR, BIGINT, TIMESTAMP]",False
4,sakila,main,country,"[country_id, country, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",False
5,sakila,main,customer,"[customer_id, store_id, first_name, last_name,...","[BIGINT, BIGINT, VARCHAR, VARCHAR, VARCHAR, BI...",False
6,sakila,main,customer_list,"[ID, name, address, zip_code, phone, city, cou...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, V...",False
7,sakila,main,film,"[film_id, title, description, release_year, la...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT, BI...",False
8,sakila,main,film_actor,"[actor_id, film_id, last_update]","[BIGINT, BIGINT, TIMESTAMP]",False
9,sakila,main,film_category,"[film_id, category_id, last_update]","[BIGINT, BIGINT, TIMESTAMP]",False
10,sakila,main,film_list,"[FID, title, description, category, price, len...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DOUBLE, BI...",False
11,sakila,main,film_text,"[film_id, title, description]","[BIGINT, VARCHAR, VARCHAR]",False
12,sakila,main,inventory,"[inventory_id, film_id, store_id, last_update]","[BIGINT, BIGINT, BIGINT, TIMESTAMP]",False
13,sakila,main,language,"[language_id, name, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",False
14,sakila,main,payment,"[payment_id, customer_id, staff_id, rental_id,...","[BIGINT, BIGINT, BIGINT, BIGINT, DOUBLE, TIMES...",False
15,sakila,main,rental,"[rental_id, rental_date, inventory_id, custome...","[BIGINT, TIMESTAMP, BIGINT, BIGINT, TIMESTAMP,...",False
16,sakila,main,sales_by_film_category,"[category, total_sales]","[VARCHAR, DOUBLE]",False
17,sakila,main,sales_by_store,"[store_id, store, manager, total_sales]","[BIGINT, VARCHAR, VARCHAR, DOUBLE]",False
18,sakila,main,staff,"[staff_id, first_name, last_name, address_id, ...","[BIGINT, VARCHAR, VARCHAR, BIGINT, BLOB, VARCH...",False
19,sakila,main,staff_list,"[ID, name, address, zip_code, phone, city, cou...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, V...",False
20,sakila,main,store,"[store_id, manager_staff_id, address_id, last_...","[BIGINT, BIGINT, BIGINT, TIMESTAMP]",False

In [8]:
films.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   film_id               1000 non-null   int64
 1   title                 1000 non-null   object
 2   description           1000 non-null   object
 3   release_year          1000 non-null   object
 4   language_id           1000 non-null   int64
 5   original_language_id  0 non-null      Int64
 6   rental_duration       1000 non-null   int64
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object
 11  special_features      1000 non-null   object
 12  last_update           1000 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), int64(4), object(5)
memory usage: 102.7+ KB

In [9]:
films.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [14]:
duckdb.sql("from films;").df()

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,<NA>,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2021-03-06 15:52:00
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,<NA>,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2021-03-06 15:52:00
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,<NA>,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2021-03-06 15:52:00
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,<NA>,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2021-03-06 15:52:00
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,<NA>,6,2.99,130,22.99,G,Deleted Scenes,2021-03-06 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,<NA>,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2021-03-06 15:52:08
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,<NA>,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2021-03-06 15:52:08
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,<NA>,6,0.99,105,10.99,NC-17,Deleted Scenes,2021-03-06 15:52:08
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,<NA>,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2021-03-06 15:52:08
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,<NA>,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2021-03-06 15:52:08